trigger: 
  paths:
    include:
    - passing-values-of-outputs-of-steps.yml

stages:
- stage: Stage1
  jobs:
  - job: Job1
    steps:
      # Set variable's value
      - script: echo "##vso[task.setvariable variable=greeting;isOutput=true]Hello World!"
        name: Step1
      # Read variable's value
      - script: echo $(Step1.greeting)
  - job: Job2
    dependsOn: Job1
    variables: 
      # Read variable's value
      greetingInJob2: $[ dependencies.Job1.outputs['Step1.greeting'] ]
    steps:
      - script: echo $(greetingInJob2)
- stage: Stage2
  dependsOn: Stage1
  jobs:
  - job: Job3
    variables:
      # Read variable's value
      greetingInAnotherStage: $[ stageDependencies.Stage1.Job1.outputs['Step1.greeting'] ]
    steps:
      - script: echo $(greetingInAnotherStage)