trigger: none

pool:
  vmImage: 'ubuntu-latest' # 'windows-latest'

jobs:
  - job:
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        connectedServiceName: $(ServiceConnectionName)
        location: 'northeurope'
        resourceGroupName: $(ResourceGroupName)
        csmFile: ./main.bicep
        overrideParameters: >
          -parameterName parameterValue
