trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  # Build the Visual Studio solution
  - template: './build-dotnet-solution-template.yml'
# Lint bicep code
- stage: Lint
  jobs:
  - job: LintBicep
    steps:
    - script: az bicep build --file ./main.bicep

# Deploy to the test environment
- template: ./deploy-to-environment-template.yml
  parameters:
    environmentType: Test

# Deploy to the production environment
- template: ./deploy-to-environment-template.yml
  parameters:
    environmentType: Prod
